name: ejemplo-entorno

conda activate ejemplo-entorno
conda env export --from-history -f environment.yml

channels:
  - conda-forge
dependencies:
  - numpy
  - matplotlib
  - ipywidgets
  - seaborn
  - pandas
  - rise
  - jupyterthemes
  - jupyter_contrib_nbextensions
